name: Run Script on ARC Runners

on:
  pull_request: # FIXME: Remove this before mergin
  push:
    branches:
      - main

jobs:
  integration:
    strategy:
      matrix:
        runner: [box-3, devops-admin-gcp-dev-usce1]
    runs-on: ${{ matrix.runner }}
    name: Run on ${{ matrix.runner }}
    steps:
      # FIXME: add basic tools to the arc runner base image
      # Missing: wget
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/bin/bash","-c","sudo apt-get update && sudo apt-get install curl unzip jq wget python3-pip git-all -y && /home/runner/run.sh"]
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Setup PostgreSQL
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: 16
      - name: Run script on ${{ matrix.runner }}
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          BUILDKIT_PROGRESS: plain
        run: |
          echo 'github' > .id
          make test
          make test-e2e
